### ISSUE TITLE
parse through entire rmd file

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#102]
hello @mbjoseph just wondering if you've ever implemented something that parses through an entire RMD file and replaces particular strings?

I have a cool knit to pdf and md flow going but i'll need to do a bit of cleaning on my RMD files to remove html still that pandoc doesn't understand. I thought i could clean the file just for knitting. 
Just wondered if you'd done this.

**Comment by lwasser** [comment]
maybe something like this

https://gist.github.com/mages/1544009

**Comment by mbjoseph** [comment]
Yes I've done that in the current implementation with rendered md files e.g., here: https://github.com/earthlab/earthlab.github.io/blob/master/processing-code/generate_posts.R#L214

A smarter approach would be to not use R and instead do this stuff in bash with `sed`: http://www.thegeekstuff.com/2009/09/unix-sed-tutorial-replace-text-inside-a-file-using-substitute-command/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+TheGeekStuff+(The+Geek+Stuff)

**Comment by lwasser** [comment]
THANK YOU!! i got it to work in my knitting workflow - pdf's for DAYZZZZZ!! closing this :)
