### ISSUE TITLE
we should get a domain name: www.earth-analytics.org is available

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#105]
@mbjoseph it is available. It's easy to remember and has analytics in it. 

we'd have to use the hyphen though.
thoughts?

The next step is we should tag lessons to help with search engine visibility. so a page of lessons on time series, raster data, python, r, etc.

**Comment by mbjoseph** [comment]
Maybe we can chat IRL tomorrow if you're around? I think there are pros and cons...

**Comment by lwasser** [comment]
sure. i'll be in tomorrow.
i'm home practicing my coughing technique today. it's all core.

**Comment by lwasser** [comment]
also - i don't think i have super powers on this site? 
i wanted to change the site description as it's dated now. 

https://github.com/earthlab/earthlab.github.io

**Comment by mbjoseph** [comment]
Ok you should have superhero status now.

**Comment by lwasser** [comment]
![]9http://gph.is/2iCeO9j)

**Comment by lwasser** [comment]
![](https://media.giphy.com/media/3o6Ztroynp3WpqLD1u/source.gif)

**Comment by mbjoseph** [comment]
For me, more commonly:

![](http://gifrific.com/wp-content/uploads/2012/08/Cat-Jumps-at-Wall.gif)

**Comment by lwasser** [comment]
hah!
