### ISSUE TITLE
Alphabetically sorted package/module names in sidebar

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earthlab.github.io#15]
Just now I found myself looking for a tutorial that used a specific Python package, and tried to use the side bar to find it. It seems like this would be easier to do if the packages were listed alphabetically. Is this possible @lwasser?

**Comment by lwasser** [comment]
Yes! A few options

Sort by library if we are looping through all posts.

{% assign sorted_posts = site.posts | sort:"order" %}

              {% for post in sorted_posts %}

Or – if the loop is looping through a yaml list (which I think it is) list all libraries alphabetically. Right now they are randomly listed. Or see if you can sort on the members loop



https://github.com/earthlab/earthlab.github.io/blob/master/_includes/sidebar.html



I don’t know if this will work but we can try

       {% assign sorted_libs = site.data.libs | sort:"libs" %} <<- add to sidebar code



          {% for member in site.data.libs %} << replace with {% for member in sorted_ libs %}



if that doesn’t make sense I can try it!

**Comment by mbjoseph** [comment]
If you've got time to test out a simple implementation, feel free! I'm
still not super comfortable tweaking the sidebar.

On Dec 9, 2016 3:19 PM, "Leah Wasser" <notifications@github.com> wrote:

Yes! A few options

Sort by library if we are looping through all posts.

{% assign sorted_posts = site.posts | sort:"order" %}

{% for post in sorted_posts %}

Or – if the loop is looping through a yaml list (which I think it is) list
all libraries alphabetically. Right now they are randomly listed. Or see if
you can sort on the members loop



https://github.com/earthlab/earthlab.github.io/blob/
master/_includes/sidebar.html



I don’t know if this will work but we can try

{% assign sorted_libs = site.data.libs | sort:"libs" %} <<- add to sidebar
code



{% for member in site.data.libs %} << replace with {% for member in sorted_
libs %}



if that doesn’t make sense I can try it!




—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/earthlab/earthlab.github.io/issues/15#issuecomment-266138829>,
or mute the thread

**Comment by lwasser** [comment]
Ok. I think I just broke the site but don’t understand how I just commented out pagination and travis yelled at me.

It builds locally. Any ideas?

**Comment by lwasser** [comment]
Ok – looking at it quickly there’s no great quick way given it’s a YAML list in the data folder (atleast that I can see) . Sorting posts on a single yaml element is very easy.

Can you just sort the list them you build it in R? If not I’ll keep digging but sorting a yaml list in R is very easy I think?

Lemme know!

**Comment by mbjoseph** [comment]
Yes.. Shoot. I'm guessing Travis is trying to build your branch and is not
finding .travis.yml and the build script, etc.

I'm in the car right now but we should be able to fix this by specifying
only to build the feature/minimal-travis-ci branch. I can do later this
afternoon!

**Comment by lwasser** [comment]
Oh yes – that is one error I  saw

Ok the PR is there and you can see the angry messages. Some of which made me cry.
If it’s not my change which is minor, then… please fix.

Lemme know about the sorting. I’ll keep digging but don’t want to spend too much time on that right now if we can just sort when the list is generated which I think is probably better.

**Comment by mbjoseph** [comment]
Ok Travis should be fine now - it will only build if `.travis.yml` is present.

**Comment by lwasser** [comment]
Ok! I broke the site about 800 times while you were away.

I’m going to turn off breadcrumbs. I remember what the issue was. They are cool but I think we have to use the auto generated page links. I’ll submit a PR with it turned off soon.

**Comment by mbjoseph** [comment]
I accidentally fixed this issue with 4de48c8f307eebf7b2ee8e3a0a6f94d06f587a3b

**Comment by lwasser** [comment]
I hate it when I accidentally fix things. Geez.
