### ISSUE TITLE
week 5 - to do

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#169]
* add code to export vector writeOGR() to the reproject vector lesson!

**Comment by SepidehD** [comment]
- [ ]  import polygon?
![image](https://cloud.githubusercontent.com/assets/16745365/23184337/9b24f794-f83c-11e6-99d3-d4f81bf71f09.png)
https://earthlab.github.io/course-materials/earth-analytics/week-5/reproject-vector-data/

**Comment by lwasser** [comment]
@SepidehD i'm not sure what this comment means. they are importing a shapefile here. can you please clarify?

**Comment by SepidehD** [comment]
@lwasser the comment is importing point, while it is polygon

**Comment by lwasser** [comment]
Ahhh that makes sense. Thank you for the clarification. If you don’t mind being a bit more specific in your feedback it will help me identify what you are calling attention to. Thank you sepideh!



Leah

**Comment by lwasser** [comment]
this has been fixed !!
