### ISSUE TITLE
travis logs not rendering?

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#180]
hey @mbjoseph when you get in to the office tomorrow can you please see if you are able to see the build logs in travis for our site? For some reason the build fails but i can't look at the logs to see where it fails.  i've tried all day today and used different browsers too!

**Comment by mbjoseph** [comment]
I only see errors too. I know that Amazon S3 crapped its pants today. Don't know whether this would be related...

**Comment by mbjoseph** [comment]
Looks like they were affected - maybe things will improve tomorrow

https://www.traviscistatus.com/

**Comment by lwasser** [comment]
Oh ok. I checked the status yesterday and everything was green ! Ok maybe it will be better this morning! I'm glad it's not just me seeing the issue. I was concerned maybe I broke something inadvertently.



________________________________

**Comment by lwasser** [comment]
Ok it's working now. I jumped the gun. It's just that all yesterday I couldn't access the logs which was concerning! I should have waited another few hours! Thanks!!

Leah A. Wasser
---
Director, Earth Analytics Education Initiative
Earth Lab, CU Boulder
twitter: @leahawasser


________________________________

**Comment by lwasser** [comment]
Closing this - it's going up and down today - works sometimes, doesn't others. i know it's not something i'm doing so i'm ok with being patient... travis can yell at me using more explicit / specific language when it's online again!
