### ISSUE TITLE
week 8 - functions lessons to do

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#192]
Hey @mbjoseph I just pushed a draft of 3 lessons to the dev-lessons branch! It includes an intro lesson with the DRY principle outlines + then the SWC function lessons broken into two sections. 

- [x] Task: @mbjoseph please have a look and edit as you see fit when you have a few today.?
- [x] Point of "attention": @mbjoseph we haven't worked with vectors much in class. We did a bit in week 2 but they won't understand concatenating vectors unless we explain it. Thus the fence function task will need to be explicetly explained. I think they will get it just know they will need an intro to that concept.  
- [x] Task (for me): Also -- I think it would be cool to have a website demo that shows the code BEFORE and after implementing functions. But i'd rather not use the code we are using tomorrow in class. I will add an example later today unless you have one already. I'm thinking i may use import raster stack and then plotRGB as an example. We are plotting using legends in class. 
- [x] Task (for me): I will clean up my script and print it out but also make it available on figshare today for week 8!

Finally i think i can do a better job with the intro lesson. it will be more clear once i see how you present things tomorrow! But again - edit away.

Thank you for being willing to help this week. The students will be happy to see a new face / voice / perspective - i'm sure!!

**Comment by mbjoseph** [comment]
Awesome @lwasser - working on it now!

**Comment by lwasser** [comment]
thank you @mbjoseph i just rebuilt and pushed back to dev-lessons. i fixed one thing - one of your function examples had a function called my_function yet you called modify_x(). i went with the  more expressive name but feel free to adjust if you don't like it! 

Thank you again for working with me on this.

**Comment by mbjoseph** [comment]
Awesome - that's what I meant to do - read my mind!
