### ISSUE TITLE
question about function etiquette 

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#195]
@mbjoseph 
when you have a few - please review this page and give me feedback:

https://github.com/earthlab/earthlab.github.io/blob/dev-lessons/_posts/course-materials/earth-analytics/week-8/in-class/2016-12-06-automation02-function-example-r.Rmd

I'd like to create a function for plot RGB. it would be easiest for a user to provide a stack and then the bands that they want to plot within that stack. However, in my first iteration i just created a stack that was in the order of how i wanted R to plot it using plotRGB(). 

How would you handle potentially adding another argument to specify the order of the layers to stack using plotRGB()? it would certainly make the code cleaner but it would add 3 more arguments 
r=4, g=3, b=2 

Perhaps a vector of numbers that is parsed in the function? 

is this bad form? Thank you for any advice! i want things to be in line with what you are teaching tomorrow!!! THANK YOU AGAIN.

**Comment by mbjoseph** [comment]
I think I'd prefer to have the three arguments instead of one vector because it's easier to understand. We can also use it to show how defaults work, and how you can pass arguments to functions within your function (e.g., feed `r`, `g`, and `b` directly to `plotRGB()`

**Comment by lwasser** [comment]
Perfect. Ok thank you, Max!
I do like the idea of having default values which is what plotRGB() does.
Leah
