### ISSUE TITLE
domain name revisited

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#239]
@mbjoseph  i've thought about our domain  name and a few are still available.
if we want to get earth lab as our name out there... 

earthlabcu.org is available for 7.99! i know how to setup it up via godaddy to link to our site.
earth-analytics.org is also available (unfortunately the dash is required)

our site is currently completely ignored by google although it has crawled it. i'm not sure why but it's time to be proactive!! what do you think about earthlabcu.org ?

**Comment by mbjoseph** [comment]
Top of the morning @lwasser! I think earthlabcu.org sounds great.

**Comment by lwasser** [comment]
Top of the morning!! ☺ Great. I’ll talk to Chelsea about purchasing it today or tomorrow. I’m happy to use my EDU budget for this.

Leah

**Comment by mbjoseph** [comment]
We could also think about selling off some of our Goldfish cracker reserves if need be - I bet we could get away with a 200% mark-up if we pair it with some cold water from the water coolers.

**Comment by lwasser** [comment]
ahhh yes - i like how you think @mbjoseph excellent business approach. maybe bring this up as a revenue stream option at our team meeting later??  ;) btw we should also emphasize the $$ in waste associated with goldfish on the floor around SEEC. i found one bugger on the stair well  the other day ! he had  jumped ship apparently due to fear of being sold in the goldfish black market.

**Comment by lwasser** [comment]
we have a manual restriction on our site as spam!! working on it.

**Comment by mbjoseph** [comment]
Ha! That's hilarious. I can imagine someone might have grabbed a handful on their way out. 

It's also worth bringing up the possibility of raising a herd of chinchillas to get some wool out of this setup (chinchilla wool - so hot right now https://www.etsy.com/market/chinchilla_wool). I'm not sure what the current carrying capacity would be for a population in our space, but I would guess we could manage to support ~ 3 - 5 head with our current rate of goldfish deposition.

**Comment by lwasser** [comment]
ahhhhh YES. i like wildlife route. it will add vibrance and energy to our lab. the earth stuff is interesting but really biology is where it's at. It could also be worth considering alpacas or LLAMAS . they could protect the chinchillas given they are a valuable species but also alpaca fur is quite a commodity itself so we could add to both lab safety and revenue to our goldfish - cooler water black market model. this is gold @mbjoseph why didn't you bring this up earlier in the semester?! 

![](https://s-media-cache-ak0.pinimg.com/600x315/b9/64/4b/b9644b384174463dbc8b73764374546c.jpg)

**Comment by mbjoseph** [comment]
Now we're talking - but what are the llamas going to be protecting the chinchillas from? Maybe it's worth getting some cats to round out the food web?

**Comment by lwasser** [comment]
I think that any well developed science Lab should involve a well rounded food chain. Solid.



________________________________
