### ISSUE TITLE
Search / filter pages

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#24]
_From @lwasser on October 17, 2016 21:52_

Jekyll builds the entire site which makes dynamic searching difficult. however one work around is to use JSON to store a record of all pages and generate a search that way

https://github.com/cobbler/jekyll-dynamic-search

we might be able to use this as a work around to generate drop downs that allow users to filter content based upon YAML elements.

_Copied from original issue: earthlab/dev-earthlab-site#7_

**Comment by lwasser** [comment]
Another implementation of this: http://jekyll.tips/jekyll-casts/jekyll-search-using-lunr-js/

**Comment by lwasser** [comment]
@mbjoseph  Ok - i just did another search and found a way to search using google.

http://digitaldrummerj.me/blogging-on-github-part-7-adding-a-custom-google-search/ 

there may be other options but google is a robust and potentially simple one!

**Comment by mbjoseph** [comment]
Sick! Looks pretty easy. 🤓

**Comment by lwasser** [comment]
It does! My api class was frustrating so maybe I'll tackle some lower hanging fruit tomorrow!! It seems super easy to implement.


________________________________

**Comment by lwasser** [comment]
closing this given the website redesign!
