### ISSUE TITLE
we are the spammiest spammers every - google SPAM flag

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#240]
Ok -- we have been flagged as a site dedicated to pure spam! oh yes.  believe it. 
Looking at our home page i realized we made a fatal error in the design. There is no dynamic content even though we've been generated TONS of new lessons every week. tons and tons. That is a flag and a poor decision on my part in terms of home page design.

Given this - i'm working on some code to add "recent modules" and recent tutorials to the home page. Possibly recent events too but @mbjoseph  i'd need you to update the meetup events on the site for this to be effective! let me know what you think. this will help with our flag as spam because they will see new content being generated. Plus... it's just better. we can talk IRL later today about this. it may be ok once we have a shiny new URL as they may see our site as a new site doing good things in life like housing hords of chinchillas and goldfish..

**Comment by lwasser** [comment]
ok @mbjoseph have a look at the search branch and see what you think about the home page. IT's not perfect but i think it's better in terms of highlighting dynamic site content . if you are ok with it i'll push it live later. The search issue will take a few weeks atleast to sort out although i'm hoping maybe a new url COULD be helpful to us. that url won't be spam tagged like ours is.

**Comment by mbjoseph** [comment]
I think the home page looks much better! Feel free to push. 

I was looking for a search bar and then realized that you mentioned you turned it off (basmati rice, right?).

**Comment by lwasser** [comment]
Yes! I turned it off because we are spam marked and it won't work till they unflag us! Boo. We r so spammy .

Sweet I'll push it live later. Thanks!

Leah A. Wasser
---
Director, Earth Analytics Education Initiative
Earth Lab, CU Boulder
twitter: @leahawasser


________________________________

**Comment by lwasser** [comment]
merged! closing
