### ISSUE TITLE
tagging revisited

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#242]
Holy potatoes @mbjoseph - i figured it out. we can use nested tagging however i suggest we use a new tag name - even if it's tag2 rather than the built in jekyll tag element. we can use the tag element for something else! So the to do's
- [x] Finish up code that loops through posts and generates counts (this requires the next step to be completed  <<LEAH >>
- [x] Tag each lesson in the course lessons <<LEAH>>
- [x] Add code to support nested language tagging system << LEAH >>
- [x] Fix tag lists on the bottom of each lesson - currently it uses our categories like course-materials, etc. Probably the topics is more useful so main tag and then sub tags... rework code.
- [x] Add nested **language** tagging system to each course lesson << LEAH >>
- [x] Auto generate a yaml file  - to replace this one -- https://github.com/earthlab/earthlab.github.io/blob/search/_data/tags2.yml from all of the posts. i think this is similar to what you are already doing with authors @mbjoseph  when
 we run make, this should capture all tags and sub tags in each post md file. <<Max? >>
- [ ]  implement the same nesting approach for languages and libraries

**Comment by mbjoseph** [comment]
💯 💯 💯 💯 💯 💯 💯 💯 💯 💯

**Comment by lwasser** [comment]
Ok - revisiting this @mbjoseph we should chat IRL about the ontology -- right now i have R and python embedded as tags in "Scientific programming" but also a nest language option. it's worth revisiting this now before doing too much more work to the site! when you feel recovered and caught up from all of your adventures, lemme know!!

**Comment by mbjoseph** [comment]
Sounds good @lwasser - maybe we can chat tomorrow after lunch?

**Comment by lwasser** [comment]
that works for me @mbjoseph !!

**Comment by lwasser** [comment]
Ok! i'm going to open a more specific issue surrounding languages and libraries and close this issue given we addressed it together today IRL!!
