### ISSUE TITLE
code block rendering

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#25]
_From @lwasser on November 29, 2016 18:33_

Current - the code is rendering

- [ ] Uuuuuuggggggly - grey is not easy to read
- [x] in blocks - that separate code from results yet the colors don't visually represent that. for the time being remove the individual blocks 

Look into tweaking rouge for better highlighting OR use highlight js again which is very nice. 

_Copied from original issue: earthlab/dev-earthlab-site#31_

**Comment by lwasser** [comment]
Use `collapse=T` in the knitr settings options$set in the script to force knitting to all code chunks. 
    
`opts_chunk$set(collapse=T)`

On to ugly code highlighting...

**Comment by lwasser** [comment]
@mbjoseph when you have a few... please have a look at the dev-code-highlight branch for a darker code block. i need to fix the line spacing and padding BUT see if you dig the color scheme. If you do i'll tweak the rest of the styles. clean it up. and merge in some other style changes i've made in the dev-lessons branch for a unified styles update PR.

**Comment by lwasser** [comment]
code stylesheets here:

https://github.com/richleland/pygments-css

**Comment by mbjoseph** [comment]
Pretty cool! I am having a hard time seeing the parentheses which are dark green on my screen (which is a terrible screen). 

Can we choose from any of these themes? http://richleland.github.io/pygments-css/

It might be nice to have one that's got a little more contrast, for folks with potato displays.

**Comment by lwasser** [comment]
yes, - this is one set of stylesheets! there are others.

1. if the green is the only color that is hard to read - or it's just a few colors- it's SUPER easy to just fix that color. I can show you how to test that on the fly with firebug unless you already know how to do that.
2. We can try another template! it's pretty easy to drop them in - you just have to change-all one thing in the text editor and rebuild the css.

**Comment by lwasser** [comment]
the green isn't easy for me to read either now that i look at it.

**Comment by mbjoseph** [comment]
Ah cool! Nice to know we have options. I'd say that if we can go with a more contrasty theme like fruity or monokai, that would be nice. Or if you're stoked on the existing theme, maybe it's a matter of brightening up that green a bit?

**Comment by lwasser** [comment]
I'd like to see the potato version first! tomorrow is kinda bizy but maybe Friday we can have a look?
I'm open. i am not crazy about super bright contrasty themes with our current mellow min mistakes feel. so let's find a middle ground!

**Comment by lwasser** [comment]
![potato](http://i.giphy.com/12a3cXp4zXY1xe.gif)

**Comment by lwasser** [comment]
ok closing this too since we are doign a web redesign!!
