### ISSUE TITLE
Earth Lab Site Title

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#252]
Hey @mbjoseph  before you leave for your super fun pre-wedding extravaganza... our website is finally being indexed by google. But what's coming up is "Earth Lab Resources" over and over.

This is not a good site title as it sounds like stuff for earth lab. Let's come up with something better like

* data lessons - earth lab
* data tutorials  & course materials
* work with data - earth lab 
* open science approaches - earth lab

any other ideas? We can change it again but i just want to optimize as much as possible now!
I plan to push the search live in the next week and my lessons will then be indexed!!

**Comment by mbjoseph** [comment]
I would vote for work with data (but is this too close to NEON's WWDI?) or data lessons or data tutorials and course materials among those. Other ideas:

- Earth data science lessons
- Earth Lab data science
- Data science lessons - Earth Lab

**Comment by mbjoseph** [comment]
Also 

![](https://www.mountainproject.com/images/69/77/106296977_large_a8b0c9.jpg)

**Comment by lwasser** [comment]
oh man!!!!! whipper territory eh? i miss climbing. i need to get back to it when i'm less obsessed with mountain running.

Unfortunately NEON does use WOrk With Data as the banner of the site SO...good point. Let's think of something different .

Let's see: I like where you're going
* Earth Data Science - Earth Lab (i actually kinda like this given data science is a buzz word now and we add earth to it)
* Earth Analytics - this term could be harder for people to understand so maybe we use it in the text throughout the site so google picks it up BUT not in the title. 

Thoughts??!!
more climbing pictures to make our hands sweat.

**Comment by mbjoseph** [comment]
I like "data science" over "analytics". They're both non-terms in their own right, but data science might be more descriptive (I often think of web analytics when people say analytics). 

![](http://www.slacklineindustries.com/assets/helen-richardson---cd16highline__2hr5957-(1).jpg)

**Comment by lwasser** [comment]
me too!! i think data science is a more clear term. So earth data science to start with? We can change it it just will help us with our rank i think to pick meaningful terms. 

on goodness high lining is so freakin scary. is that eldo? cause i love me some eldo.

**Comment by lwasser** [comment]
hey @mbjoseph so while you were gone, i got earthdatascience.org as a domain name given we landed on that before you left. SHould we use it here?

In an ironic series of events it turns out that my program is likely going to be named earth-data-analytics 

Google says:
* Analytics is discovery, interpretation, and communication of meaningful patterns in data
* Data science, also known as data-driven science, is an interdisciplinary field about scientific methods, processes and systems to extract knowledge or insights from data in various forms, either structured or unstructured, similar to Knowledge Discovery in Databases (KDD).

The only thing i don't like is that data science doesn't seem to inherently include communication. 

Anyway thoughts? Google is finally indexing our site!! slowly...

**Comment by lwasser** [comment]
oh also @mbjoseph it does seem that data science is a better key word -- more known than analytics... and i don't have the url. i'm just keen to get the URL in place as it takes so long to index things.!

**Comment by mbjoseph** [comment]
I'm fine with either - still leaning toward data science over analytics. Plus, I like that earthdatascience.org differentiates the content here from pure "earth lab" content. That said, I'm happy to go with your gut on this one!

**Comment by lwasser** [comment]
I actually really like earthdatascience.org a lot and that's why i bought the domain! Let's go with it @mbjoseph if you are on board !! :) I think in the end the URL is important to get visibility BUT really the text on our pages will drive traffic!!  So those excerpts, tags, etc are HUGE. Also i don't like data-analytics two a's next to each other. eek. 

So - maybe when we talk we should  

- [ ] Decide when to apply the domain. I'm guess some things could break potentially. maybe not but maybe... 
- [ ] revisit the tagging ontology and talk about applying it to the tutorials too 
- [ ] talk about how / if we want to somehow differentiate between a tutorial and a course series. Lots of options to do this (or not!!?) tactfully!

**Comment by lwasser** [comment]
Ok - DNS servers are now setup to forward earthdatascience.org to our git site. Once we add a CNAME to our git repo it will be ready to go (1-2 days to propagate)  yeeassss ... so it's just sitting for now!

**Comment by lwasser** [comment]
I'm going to close this!! we have a plan to implement the new URL on Friday!! :)
