### ISSUE TITLE
Brainstorm -- Time series sub topics

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#260]
This issue is to flesh out a few time-series related sub-categories! I started to brain storm this ...
I already teach convert-dates although that's not the best set of words that people would search on. Convert-string-to-date?

Let me know what you think @mbjoseph (when you're back in the office at a reasonable time of the day)!!
```
time-series:
    topics: ['epoch',  'julian-day', 'day-of-year', 'convert-date-time']
```

**Comment by mbjoseph** [comment]
Hiya @lwasser!

Is there an advantage of going singular vs. plural? I'm wondering whether `julian-day` is more or less visible than `julian-days`. 

I would also add `date-time` or `convert-date-time` to the list if people have time of day data.

**Comment by lwasser** [comment]
@mbjoseph  I added convert-date-time my guess is the pural shouldn't be a huge issue as generally i think search engines know how to deal with those types of things so they can search more effectively BUT with that said - what do you think is more common? let's go with that? i don't know.

**Comment by lwasser** [comment]
Also - think if we have convert dates then convert-date-time probably is just broader. i'd suggest we remove convert-dates to keep things clean!!

**Comment by mbjoseph** [comment]
Roger dodger. I agree `convert-date-time` is probably more general. I think the singular version is probably more common, but that's just a hunch!

**Comment by lwasser** [comment]
ok done!! closing this. thanks for the input!
