### ISSUE TITLE
Google analytics permissions

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#269]
Hey @mbjoseph did you setup Google analytics for earthlab? If so can you please give me super powers? (using my cu email) ?

**Comment by mbjoseph** [comment]
You are now super powered! 

![](http://1funny.com/wp-content/uploads/2012/01/tiny-superheros.jpg)

**Comment by lwasser** [comment]
![](https://media.giphy.com/media/xT8qBp0R5SxfLMIgjC/giphy.gif)
