### ISSUE TITLE
Duplicate map keys in yaml front matter`

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earthlab.github.io#274]
In the process of updating our `make` workflow, I ran across a duplicate `course` field in the front matter of `_posts/course-materials/earth-analytics/week-1/setup-r-rstudio/2016-12-04-setup-01-r-rstudio.md`. 

One of the entries is `"Earth analytics"` and another is `'earth-analytics'`. In looking at the rest of the posts, it seems like `earth-analytics` is the preferred entry. I am going to keep that one, but if you want to do something else, let me know @lwasser!

**Comment by lwasser** [comment]
Cool! i want to use all lower case! Thank you for finding this ☺ I will eventually need to build a YAML list of courses but I haven’t thought out the use cases just yet !!
