### ISSUE TITLE
Duplicate Reproducible Science Curriculum Community authors

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earthlab.github.io#277]
Heya @lwasser - it looks like we have duplicate authors for the reproducible sci curriculum stuff. We have both "Reproducible Science Community" with slug `reproducible-science-community` and "Reproducible Science Curriculum Community" with slug `reproducible-science-curriculum-community`. 

We should keep just one (the second?), and update all of the necessary code/posts to reflect this! If you let me know which you want to use, I can make the changes.

**Comment by lwasser** [comment]
yes... let's keep 

`reproducible-science-curriculum-community` 

Also i think there are a few other author duplicated - possibly neon data skill and skills ? thank you for catch these things!! let me know what you need on my end. i can always do a global search and destroy in ATOM if need be.

**Comment by lwasser** [comment]
ok -- if this looks good we can close this 

299476c9e39e28666d454b15af913e20afc0ee8e 

lemme know what else you catch! i can't find NEON Data Skill anywhere. i'm wondering if somehow i fixed it but the YAML list still has the duplicate via some iteration of make????

**Comment by mbjoseph** [comment]
Stupendous. That did the trick! Thanks @lwasser

**Comment by lwasser** [comment]
sorry - also note that there are several residual .md files ... how should we handle this @mbjoseph  ?? manual delete? i'm happy to delete now but just want to check before i do so!

**Comment by mbjoseph** [comment]
I will keep an eye out for extra stuff associated with NEON data skills authors.

**Comment by mbjoseph** [comment]
I can set this up to clean the author md files before writing new ones - that should keep us from having 1) orphan md files, and 2) manually deleting things.

**Comment by lwasser** [comment]
yeeassssss orphans sound sad. and i'm too tired to manually delete things so  👍 👍 👍

**Comment by mbjoseph** [comment]
Yes my brain is not very good at set operations anyway, even when I'm totally alert!
