### ISSUE TITLE
Update author biographies

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earthlab.github.io#278]
Our `org/author-bios.csv` file could use some bio entries. I can fill in the entries for Analytics Hub people, but it would be great it @lwasser can fill in some bios for other people!

**Comment by lwasser** [comment]
@mbjoseph do you think i can include url's and such in the bios? i can work on this -- maybe not immediately but in the next week.

**Comment by lwasser** [comment]
@mbjoseph  me again - can you please remind me -- do i add authors manually to this list? i noticed some are not here so it's not a part of our make workflow? is that correct?

**Comment by mbjoseph** [comment]
Hey @lwasser 

1) I don't think URLs work in the author bios, based on the way this page renders: http://earthdatascience.org/authors/neon-data-skills/

2) As it currently stands, we need to add authors manually to the csv file, along with their bios.

**Comment by mbjoseph** [comment]
Closing (out of date)
