### ISSUE TITLE
travis is freaking out

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#336]
hey @mbjoseph i have no idea why but travis all of a sudden has issues with our https protocol. 

just a notice - if you happen to know what is going on please let me know. if not... maybe it will settle down later today?

**Comment by mbjoseph** [comment]
yeesh @lwasser - I have no clue what's happening here.

**Comment by lwasser** [comment]
ok... i've tried several things... if it's still doing this tomorrow... is it worth looking into this

https://stackoverflow.com/questions/41522256/how-can-i-avoid-travis-ci-ssl-errors

i can also contact cloudflare who is handling the ssl but it seems to me the site is working just fine ...
thanks @mbjoseph  i don't know what triggered this... it's been just fine. for weeks now.
