### ISSUE TITLE
differences w min mistakes

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#5]
I have noticed a few differences between this template and min mistakes.

- [x] Earth lab site is that it is not registering as secure. This has something to do with the https but i'm not sure what is triggering security issues. With other sites i've noticed a link to an outside .js script causes issues but i haven't yet tracked one down with our site? 
- [x] The _sass dir is missing in earth lab. This fixed rendering issues on my local site but we should try to post a file with a nav bar to test. to add a navbar :
```
sidebar:
  nav: "spatial-intro"
```
https://github.com/lwasser/R-Spatio-Temporal-Data-and-Management-Intro/blob/gh-pages/02a-about-vector-data-shapefiles-R.Rmd

then add to the navigation.yml file a spatial intro nav yml list

https://github.com/lwasser/R-Spatio-Temporal-Data-and-Management-Intro/blob/gh-pages/_data/navigation.yml

see:  	e476328

**Comment by lwasser** [comment]
security issue seems to be resolved - 1905cb8234598206a64067654d0d8179310399b3 !!

**Comment by mbjoseph** [comment]
The rendering issue is resolved too with f4f160c. Yay.

**Comment by lwasser** [comment]
yes. we are obvious masters of js and all things https now. let's close this!
