### ISSUE TITLE
make file failing - r code error

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#503]
hey @mbjoseph i wondered if you had energy to revisit our make file. when i run it these days i'm getting the error below. it seems to be happening on this apply statement with `yaml2df`. do you have any time to have a look? i've been manually adding authors but it would be nice to have this functionality back to do it automagically and check things as we go. 
```
lapply(md_files, yaml2df, "authors")
 Show Traceback
 
 Rerun with Debug
 Error in (delims[1] + 1):(delims[2] - 1) : NA/NaN argument 
```

**Comment by mbjoseph** [comment]
This is a blast from the past @lwasser! I will take a look.
