### ISSUE TITLE
too many branches!

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#519]
hey @mbjoseph  we have a LOT of very dated branches here and it's becoming unweildy to manage. are you OK with removing old / stale branches from our repo? i've been removing some of mine. they are not being used and make it hard when submitting PR's as our site grows!! But i want your OK before cleaning up things. And perhaps you could delete some of the very old ones that you have created that your comfortable with removing!

**Comment by mbjoseph** [comment]
Indeed! I just deleted a bunch of mine, but left yours alone. Crazy to think some of these are already 2 years old.

![](https://media.giphy.com/media/qjCAPSOtefNoA/giphy.gif)

**Comment by lwasser** [comment]
I know, right? i was thinking the same thing!! time really goes by quickly!! Thank you so much @mbjoseph i'll continue to clean up branches. believe it or not i removed a lot of mine last week and STILL there are more :)

**Comment by lwasser** [comment]
ahhh so much better. thanks!! i'm happy seeing that cleaned up!  closing this!
