### ISSUE TITLE
Make Workflow

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#52]
Right now the make workflow requires a suite of R packages. Are these documented somewhere to ensure a build? OR is there a way to not force rebuild of EVERY less?
so far i've had to install as not having them crashes out `make`. 

* lubridate, rlist, viridis

If you have any ideas with respect to how to refine this process, i'd like to hear them @mbjoseph 

i'm also noticing that there are many unnamed r code chunks as it's building the R tutorials" 

Finally - i'm not sure it's looking for authors in my lessons as well? is it?

**Comment by mbjoseph** [comment]
The R packages required to build the site aren't documented officially anywhere, which is a problem. 

We should be able to avoid rebuilding lessons by comparing the date of file creation or last commit between the md and the source file. 

I have been lazy with Rmd and tend to not name all my code chunks. I'm happy to change this if you'd rather have all code chunks be named. 

Currently author verification happens only for files in the `_posts` directory, but it sounds like you'd like to have verification for things in `_drafts` too. 

Four issues?

**Comment by lwasser** [comment]
THANK YOU for the clarification. Sounds like a suite of issues. I can make them if you’d like.

Sorry, Max. So many things keep coming up as I work on things.

Yes I’d like to build lib and author name files against _drafts as well. Named chunks is super minor.

**Comment by mbjoseph** [comment]
No worries! Thanks for asking - it's one thing knowing that there are
wrinkles to iron out, an another knowing exactly which wrinkles need
ironing. I'll open these as issues and close this one.

**Comment by lwasser** [comment]
Thanks!
