### ISSUE TITLE
Can you kindly help me troubleshoot alt tags? & some broken links

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#522]
Hey @mbjoseph  me again... 
now that i have the site mostly working... i'm going through and fixing missing alt tags...
Would you be open to helping  me update the git workshop that we did? See below. 

![screen shot 2018-07-30 at 9 23 17 am](https://user-images.githubusercontent.com/7649194/43406848-55acaed8-93da-11e8-9550-02c61e426521.png)

What you'd need to do is go here:

https://github.com/earthlab/earth-analytics-course-materials/tree/master/_posts/workshops/version-control

Anytime you see this - an image with no alt tag
`<img src="http://www.phdcomics.com/comics/archive/phd101212s.gif">`

change it to
`<img src="http://www.phdcomics.com/comics/archive/phd101212s.gif" alt = "alt tag text goes here">`

My goal is to chip away at all of these issues throughout the site slowly with the goal of getting closer to a clean travis build!! Are you ok with helping with this? i can rebuild the lessons if you submit a pr with the changes? 

HERE is a travis build for reference where you can see a bunch of missing alt tags!  https://travis-ci.org/earthlab/earthlab.github.io/builds/409898781#L871

**Comment by lwasser** [comment]
hey @mbjoseph  me again -- i also found some bad links in the tutorials. Please see here:
https://travis-ci.org/earthlab/earthlab.github.io/jobs/409901460#L898

I suspect that some of these links may  be OK. if they are ok we can ignore the error using the `data-proofer-ignore` argument as follows:   

### Ignore a link that is not passing HTML proofer but we know works:
HTML url:
```
<a href="http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.9.516&rep=rep1&type=pdf" target="_blank" data-proofer-ignore=''>
```

Markdown url:
```
[get pdf](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.9.516&rep=rep1&type=pdf){:data-proofer-ignore=''}
```

![screen shot 2018-07-30 at 10 49 07 am](https://user-images.githubusercontent.com/7649194/43411039-39e81186-93e6-11e8-8bd9-055e9c99a283.png)

It seems like a bunch of the petalibrary links are actually BAD. but sometimes html proofer also flags links that are slow which we can ignore if they still work. unless you have a better solution!

**Comment by mbjoseph** [comment]
Heya @lwasser yes I'm happy to help fix these. This week and next are pretty busy for me, but I should have some time later this month after ESA to work on this!

**Comment by lwasser** [comment]
Thank you Max!!
