### ISSUE TITLE
earth analytics course week 1 revisions

### ISSUE THREAD

**Issue by SepidehD** [earthlab/earthlab.github.io#58]
hey @lwasser here are some issues i've found with our course:
# Week one edits
- [x] we need an assignment page for week one homework - please create and add it to the sidebar
- [x] The font is small here:
http://localhost:4000/course-materials/earth-analytics/intro-rmarkdown-knitr3

## rmd lessons
- [x] issue one

**Comment by SepidehD** [comment]
![image](https://cloud.githubusercontent.com/assets/16745365/21200864/0f80d3b4-c206-11e6-8cd4-07e1f0486762.png)

- [ ] please look at this!

**Comment by lwasser** [comment]
hey @SepidehD i made the change - update your dev-lessons branch locally and see how it looks

**Comment by SepidehD** [comment]
Looks good! thanks


*- - - - - - - - - - - - - - - - - - Sepideh Dadashi*
Graduate Student and Research Assistant
University of Colorado at Boulder

**Comment by lwasser** [comment]
Great!

**Comment by lwasser** [comment]
closing this as it was fixed!!
