### ISSUE TITLE
Travis CI - ALt Tag

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#65]
Hey @mbjoseph I'm noticing errors with missing alt tags on my pages. It's easy to fix when i've added the graphics but with knit pages, it isn't there. How did you handle that on the python / notebook side given you can't manually add the alt text for each figure?

**Comment by mbjoseph** [comment]
Ah I was struggling with this for a while. If I recall, the solution was to use the code chunk option `fig.cap` and also to make sure that when rendering posts, we are outputting GitHub flavored markdown: https://github.com/earthlab/earthlab.github.io/blob/5bc50fe3995b56ba6d87c1426ac2f3a31566e6e6/processing-code/generate_posts.R#L42

**Comment by lwasser** [comment]
Ok got it!! Thanks!! Down to 2 errors both small!

Leah A. Wasser
---
Director, Earth Analytics Education Initiative
Earth Lab, CU Boulder
twitter: @leahawasser

________________________________

**Comment by lwasser** [comment]
closing!
