### ISSUE TITLE
week1

### ISSUE THREAD

**Issue by SepidehD** [earthlab/earthlab.github.io#71]
Hi Leah,

I cannot download data from this link.

![untitled](https://cloud.githubusercontent.com/assets/16745365/21488256/9b7e9fb6-cb9a-11e6-94e3-e1c7aa0da971.jpg)

If you agree, I suggest to have a DATA folder for each week that contains all required data for that week.
We can add the kmz file in DATA folder of week 1, instead of above link.

Best,
Sepideh

**Comment by SepidehD** [comment]
As you can see in the following figure, there are two same link ( CO flood-google earth). one of them should be removed.

Best,
Sepideh
![image](https://cloud.githubusercontent.com/assets/16745365/21488664/c4e62a04-cb9f-11e6-9c62-5b80f33e7fd5.png)

**Comment by SepidehD** [comment]
Hi Leah,

There are two different precipitation graphs with the same title:
"Total monthly precipitation- Boulder Co Station". Do we need to keep both?

![image](https://cloud.githubusercontent.com/assets/16745365/21489448/10c52134-cba8-11e6-9acd-59d28ce8553b.png)


![image](https://cloud.githubusercontent.com/assets/16745365/21489465/34b92f9a-cba8-11e6-89e0-1d8ba6af50a3.png)


Best, 
Sepideh

**Comment by SepidehD** [comment]
After precipitation graphs,there are some questions such as  "What differences to you see between 2012 and 2013?"
Answer to these questions is not easy without a snapshot of monthly precipitation of 20012 and 2013.
( Although the precipitation map is interactive).

Best,
Sepideh

**Comment by lwasser** [comment]
Hey @SepidehD for some reason i didn't get any notifications about this issue! i've changed my setting so hopefully i get them in the future but just in case - please ping me using @lwasser so hopefully i get sent the issue!! i'll look at these items now!

**Comment by lwasser** [comment]
<img width="653" alt="image" src="https://cloud.githubusercontent.com/assets/7649194/21570254/96c4194e-ce81-11e6-891a-0cabbc2cf224.png">

**Comment by lwasser** [comment]
@SepidehD i've fixed the data! I agree on the data. I have started folders in figshare

https://figshare.com/articles/CO_Flood_2013_-_Classroom_Lab/4295360

what do you thnk? you can download the entire set of files in batch. or can download just one file from R using download.file()

**Comment by lwasser** [comment]
<img width="643" alt="image" src="https://cloud.githubusercontent.com/assets/7649194/21570328/413736fe-ce82-11e6-90d7-c7089d6dfaac.png">
fixed!

**Comment by lwasser** [comment]
ok - i've fixed this all. Have a look again and let me know what you think. If things look good, let's close this issue and create another one if you find more issues. Thank you @SepidehD !!

**Comment by SepidehD** [comment]
@lwasser 
Hi Leah,
Thank you for your reply. The figshare is a good idea.

There is a miss spelling here (use):
![untitled2](https://cloud.githubusercontent.com/assets/16745365/21595169/27fc3dc0-d0e8-11e6-85a3-da7cf7c6e576.jpg)


"Create a new Rmarkdown file" may not be clear. it will be better if you mention it is under File form main menu.
![image](https://cloud.githubusercontent.com/assets/16745365/21595211/9be50af0-d0e8-11e6-90d1-e176e00100c2.png)

Best,
Sepideh

**Comment by lwasser** [comment]
thank you @SepidehD -- can you update your files and make sure you have the most current ones? Then tell me if you still have a problem creating the file. I put a video in there to walk the user through creating one. but also you may have dated files because i did this last week.

If not - please let me know! Also, can you please add a LINK to the file when you post an issue like the one above? it's ok if it's the localhost:4000/course-materials etc link. just so i can see what file you are looking at to compare and make sure it's current :)

**Comment by lwasser** [comment]
I found the mis spelling - just can't find the other issue where they don't know how to create a file!

**Comment by lwasser** [comment]
oh @SepidehD  is it this file?? http://localhost:4000/course-materials/earth-analytics/week-1/intro-rmarkdown-knitr2/ not the first one?

**Comment by lwasser** [comment]
ok @SepidehD please download the latest version and see if it's more clear

721416106e4dfa6dae858c6f5038980efaa2aba0

If it is - please close this issue! then we can create a new issue for other things you see in Week 1! If it is still not good, please let me know. 

I'm going to spell check everything. i haven't done that yet.

**Comment by SepidehD** [comment]
@lwasser 
Hi Leah,

I was updating all the time, but I was using "git pull" instead of " git pull origin dev-lessons" and that was the problem. Sorry!
Everything looks very clear. I went through all the steps from downloading Rstudio to using codes. All the steps were clear. 
I have no problem creating the file. 
The fonts are large enough to read. As a student, I can say the structure of presenting materials is very good.
If you agree, I close week 1 and week 2.

Please let me know if I can help in any part.

Best,
Sepideh

**Comment by lwasser** [comment]
Hey @sepideh – awesome! I wondered ☺

So – please have a look at week 2. Feel free to close any issues that you think I’ve covered.

While you’re going through things, can you please check the following:

Check out this page

http://localhost:4000/course-materials/earth-analytics/week-1/intro-rmarkdown-knitr/

See how the top box has learning objectives with a little hat icon next to it and what you need has a little check box next to it. Can you check the pages and make sure I’m doing this on all of them? Then create a new issue with a list of pages that I need to add icons to OR learning objectives..

**Comment by lwasser** [comment]
![screen shot 2017-01-03 at 10 17 03 am](https://cloud.githubusercontent.com/assets/7649194/21616230/ef43a200-d19d-11e6-9791-9fc4793d4486.png)

**Comment by lwasser** [comment]
Also any box that is orange - an activity should be labeled either challenge or activity adn should have a pencil icon like this:

![screen shot 2017-01-03 at 10 18 43 am](https://cloud.githubusercontent.com/assets/7649194/21616273/124703f0-d19e-11e6-949b-3d16b9670fd0.png)

**Comment by lwasser** [comment]
@SepidehD please create links to each page i need to fix - just copy the link in your browser into the list. let me know if this doesn't make sense!

**Comment by lwasser** [comment]
hi @SepidehD  can we close this or did i miss fixing things? Thank you.
