### ISSUE TITLE
Where can I download cloud free data?

### ISSUE THREAD

**Issue by zouhx11** [earthlab/earthlab.github.io#723]
I can't find  the 'cold-springs-landsat-hw' folder in Cold Springs Fire Data

**Comment by lwasser** [comment]
hey @zouhx11  that data is data you need to download as a part of  week 8.  can you please provide a URL where you see that directory name referenced? 

this lesson shows you how to download the cloud free data
https://www.earthdatascience.org/courses/earth-analytics-python/multispectral-remote-sensing-modis/get-landsat-data-earth-explorer/

**Comment by lwasser** [comment]
closing this as there have been no responses in a few months!!
