### ISSUE TITLE
HTML Proofer / travis

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#73]
Hey @mbjoseph travis is really becoming a time sync. I'm not sure how html proofer proofs things but it's often saying images aren't there that i see clearly are. or links don't work that clearly do.

Can we fix this? it is really consuming a lot of my time. It's useful if it finds actual broken links and missing alt tags. but sorting through everything and missing / that actually don't impact the url working is a bit tedious. 

please let me know what you think.

**Comment by mbjoseph** [comment]
I guess the quickest fix would be to remove this line: 
https://github.com/earthlab/earthlab.github.io/blob/dev/script/cibuild#L5

I'm fine with this, if you want to remove it!

**Comment by lwasser** [comment]
Ok! Let me try a few more things today to understand what it is doing. I got frustrated last night.  Thank you max.

**Comment by lwasser** [comment]
@mbjoseph I have a FIX for these pesky links that are OK but are too slow for html-proofer

https://spock.rocks/tech/2016/03/21/basic-jekyll-site-tests.html

we can tell it to ignore particular problematic links that we know are ok
just add `data-proofer-ignore- to your url as i did below. 

if you use a markdown url
`<a href="http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.9.516&rep=rep1&type=pdf" target="_blank" data-proofer-ignore=''>`

`[get pdf](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.9.516&rep=rep1&type=pdf){:data-proofer-ignore=''}`

if this works for you - then we can close this issue! i am getting successful builds now using this :)

**Comment by mbjoseph** [comment]
Bravo - that sounds like a great solution! I'm fine with closing this one.
