### ISSUE TITLE
Add dynamic table of contents to main page of Intro to EDS textbook

### ISSUE THREAD

**Issue by jlpalomino** [earthlab/earthlab.github.io#776]
The [first page of the textbook](https://www.earthdatascience.org/courses/intro-to-earth-data-science/) has a table of contents that is currently manually updated. The request is to replace this manually updated table with a dynamic table of contents that is populated as new sections and chapters are added. 

The current code for the table of contents is a Markdown table that is manually updated: 
```
| Section 1: Open Reproducible Science Workflows |
|:----------------------------------------------------------|
| Chapter 1: Open Reproducible Science            | 
| Chapter 2: Bash / Shell  |
| Chapter 3: Jupyter for Python   |

| Section 2: File Formats for Earth Data Science |
|:----------------------------------------------------------|
| Chapter 4: Text File Formats for Earth Data Science   |
```

Renders as follows:
![Markdown table of contents](https://user-images.githubusercontent.com/4017492/64629295-2b8ee280-d3b0-11e9-8c96-02af8c9c4921.png)

**Comment by lwasser** [comment]
awesome. this will be a fun little project. i'm pretty sure i can knock this out this week @jlpalomino !! :) thank you for such an explicit issue, the markdown code will make it very easy for me to create this.

**Comment by lwasser** [comment]
@jlpalomino ok i've written a little include that i hope will work for this.

try to add this to the course homepage 
`{% include textbook-toc.html %}` and let me know how it goes. this will only work if you pull down this branch. if it works, i can merge this. it is building for me locally right now just fine.

Also i noticed that this landing page has a date in the name of 2018-07-09 which is not correct. can you kindly update that date? that date turns into the created date in jekyll. 

Finally i think we need authors on the landing page for this all to work. so there are a few other changes to make.

- [ ] update course home page name so the date represents when we started the book
- [ ] add authors to this page 
- [ ] test the include above and let me know if it generates a nice table for you! if it does it will update as you add content over time!!

**Comment by lwasser** [comment]
this has been implemented @jlpalomino now you just need to update the pages. i'll go ahead and do it for the github section / pages.

**Comment by lwasser** [comment]
completed via #784
