### ISSUE TITLE
Release #?? moving dev --> master

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#78]
good morning @mbjoseph  So i'm getting close to a "release".

I'd like to push things live to test everything out well before my course begins. I'm happy to do this as a release BUT i also know i'm going to need to make frequent updates to my content so content development needs to be more agile than releasing functionality. this means i may want to push to master sometimes (text edits, etc as students and I find issues). Can we chat about a workflow sometime in the near future? We could even skype or slack or whatever if you are working this week or talk in person at the end of next week? whatever works for me.

**Comment by mbjoseph** [comment]
Any sense for when we're going to be ready to pull the trigger on this one?

**Comment by lwasser** [comment]
hey @mbjoseph I feel good about doing it soon if not in the next day or two. I know i'll have content edits over the next week but i would like to see the site live.

**Comment by lwasser** [comment]
hey @mbjoseph i'm not sure if i did this right

https://github.com/earthlab/earthlab.github.io/releases/tag/1.0

these is something weird about the release content as it just has one commit rather than a suite of commits?? no rush but when you have a few have a look! the site is live and working 👍 yeasssssss

**Comment by lwasser** [comment]
i am closing this - i made this release and we don't need to re-address it at this point!!
