### ISSUE TITLE
Link to R course needs to be re-added to main page of earthdatascience.org under Online Earth Data Science Courses

### ISSUE THREAD

**Issue by jlpalomino** [earthlab/earthlab.github.io#782]
The R course is missing from the list of courses on the main page of earthdatascience.org and needs to be added under Online Earth Data Science Courses:

![image](https://user-images.githubusercontent.com/4017492/64720297-5f890700-d487-11e9-9624-dcc3fcd9ebeb.png)

**Comment by lwasser** [comment]
thank you @jlpalomino ... easy fix. it was a mismatch in files and i had to do a manual update. easy peasy :) the fix should be live in 5 minutes and then we can close this!! great catch!! phew.

**Comment by lwasser** [comment]
fixed!! closing this. thanks again. also fixed the logo while i was at it.
