### ISSUE TITLE
do we need read time on the posts?

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#8]
hey @mbjoseph the read time on the posts is driving me a bit nuts. it doesn't necessarily relate to the read time of the page because our pages contain code and other stuff on them. Are you ok with my removing it for the time being (i'll just comment it out).

**Comment by mbjoseph** [comment]
Totally - it was on by default and although it's kind of cute, I don't think it will be missed! Feel free to comment out the relevant lines or remove altogether.

**Comment by lwasser** [comment]
Great! In the name of cuteness, we could create a time estimate front matter element and populate it with more reasonable estimates?
Or not as that would take brain power for each lesson.

For the time being I’ll comment it out ☺
