### ISSUE TITLE
Learning objectives issues

### ISSUE THREAD

**Issue by SepidehD** [earthlab/earthlab.github.io#80]
@lwasser 
Hi Leah,

please look at the following issues:

Week 1:
You may want to have a constant format for all lessons. To have a constant format, "Things You’ll Need To Complete This Lesson" could be replaces by " What You Need". Also, there is not small box before them. Please ignore following list if you think "Things You’ll Need To Complete This Lesson" is  fine.

some of the following item also dont have learning objectives. I add "missing LO" at the beginning of them.

- [x] http://localhost:4000/course-materials/earth-analytics/week-1/co-floods-1-intro/
- [x] http://localhost:4000/course-materials/earth-analytics/week-1/co-floods-data-example-r/
- [x] http://localhost:4000/course-materials/earth-analytics/week-1/precip-discharge/
- [ ] "missing LO". Maybe it doesn't need learning objective. http://localhost:4000/course-materials/earth-analytics/week-1/instructor-notes/ 
- [x] http://localhost:4000/course-materials/earth-analytics/week-1/intro-rmarkdown-code-chunks/
- [x] http://localhost:4000/course-materials/earth-analytics/week-1/knit-rmarkdown-document-to-pdf/

- [x] the color of learning objective is orange instead of blue. 
http://localhost:4000/course-materials/earth-analytics/week-1/intro-to-markdown/

- [x] has different pencil icon: http://localhost:4000/course-materials/earth-analytics/week-1/knit-rmarkdown-document-to-pdf/
![image](https://cloud.githubusercontent.com/assets/16745365/21687873/202092c6-d328-11e6-9df5-9430648b6f07.png)

- [x] you mentioned that you are going to check the spell later. but just for your information:
in the main list of week1, in " in class materials" , CO is written Co.
http://localhost:4000/course-materials/earth-analytics/week-1/co-floods-data-example-r/
![image](https://cloud.githubusercontent.com/assets/16745365/21685293/4c7d22f8-d31e-11e6-82fb-9a38af5d29b6.png)

**Comment by SepidehD** [comment]
@lwasser 
Hi Leah,

week2
- [ ] in the main menu, there is no item 2. ( it is item 3 after 1)
![image](https://cloud.githubusercontent.com/assets/16745365/21725114/3e045bb6-d3f4-11e6-923a-18d6f8aabc86.png)
-[ ] the color of challenge box is blue ( should be orange always?)
http://localhost:4000/course-materials/earth-analytics/week-2/spreadsheet-data-in-R/
- [ ] the color of challenge is blue
http://localhost:4000/course-materials/earth-analytics/week-2/write-clean-code-with-r/
- [ ] "what you need" is in different font size , and doesnt have check box 
http://localhost:4000/course-materials/earth-analytics/week-2/precip-in-r/
- [ ] "what you need" is "Things You’ll Need To Complete This Lesson". also, doent have the check box.
http://localhost:4000/course-materials/earth-analytics/week-2/co-floods-USGS-stream-discharge-r/
-[ ] please check "what you need". it is in different format.
http://localhost:4000/course-materials/earth-analytics/week-2/precip-in-r/
- [ ] please check "what you need"
http://localhost:4000/course-materials/earth-analytics/week-2/co-floods-USGS-stream-discharge-r/
- [ ] please check "what you need"
http://localhost:4000/course-materials/earth-analytics/week-2/precip-in-r/
- [ ] please check "what you need" part.
http://localhost:4000/course-materials/earth-analytics/week-2/co-floods-USGS-stream-discharge-r/
- [ ] there is number 5 in the main list.
![image](https://cloud.githubusercontent.com/assets/16745365/21725583/40847504-d3f6-11e6-8c56-7b88e41e0336.png)

**Comment by lwasser** [comment]
hi @SepidehD i have fixed everything here EXCEPT for the instructor notes. I'd like to update those each week AFTER we teach that weeks' content. So if everything else looks good, please close this issue. Thank you for catching all of this.
