### ISSUE TITLE
How Do We Collect Homework Assigments? Does CU have a platform for this?

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#82]
We need to figure out HOW students will submit homework to us. What does the university use? can we setup a drop box for them to use on d2l?

Then make sure each week assignment has a DATE and instructions how to submit homework.

@SepidehD  can you help me with this? How do other classes work at CU? how do you normally submit assignments?

**Comment by lwasser** [comment]
Things to fix in homeworks

- [ ] Date and name needed for activity: http://localhost:4000/course-materials/earth-analytics/week-1/intro-to-markdown/

**Comment by SepidehD** [comment]
Hi Leah,

Most of the times we use D2L for submitting assignments, however some
professors prefer submitting by email.

I will ask to see how we can set the D2L for this class and let you know.

I closed issues for week 1 and learning objectives.

Best,
Sepideh




*- - - - - - - - - - - - - - - - - - Sepideh Dadashi*
Graduate Student and Research Assistant
University of Colorado at Boulder

**Comment by lwasser** [comment]
Hey Sepideh. We have a  d2l space already setup. I just haven’t used it before so I was wondering how it’s normally used and if it’s useful?

**Comment by SepidehD** [comment]
Hi Leah,

I have no access to D2L for this class yet.
Can we set that up for me on Friday?

Best,
Sepideh


*- - - - - - - - - - - - - - - - - - Sepideh Dadashi*
Graduate Student and Research Assistant
University of Colorado at Boulder

**Comment by lwasser** [comment]
Ok - we have this all setup now! i am closing this issue. thank you @SepidehD !!!
