### ISSUE TITLE
Inverted hillshade colormap in lesson 6 for chapter 4 in intermediate textbook

### ISSUE THREAD

**Issue by mh-skjelvareid** [earthlab/earthlab.github.io#994]
This is the first time i file an issue on GitHub, so excuse me if I don't follow all conventions - just trying to help. :)

I have been working though the lessons in the intermediate earth data science textbook. Lesson 6 in chapter 4 ( https://www.earthdatascience.org/courses/use-data-open-source-python/intro-raster-data-python/fundamentals-raster-data/raster-data-exercises/ ) uses a hillshade dataset.

The "target" hillshade image looked a bit weird to me - the valley seemed to be "sticking up" and the buildings on the right side look like rectangular holes in the ground. However, if the hillshade is plotted with an inverted gray colormap, where the "high end" is white (e.g. "gray") it looks correct. 

I suggest changing the "target" plot images (for challenges 1-3), and changing the text to recommend using cmap="gray" rather than cmap="Grays".

Current image in textbook:

![image](https://user-images.githubusercontent.com/16107898/106142230-870e6b80-6171-11eb-9087-36a09374e3ab.png)

Hillshade plotted with "gray":

![image](https://user-images.githubusercontent.com/16107898/106142409-bcb35480-6171-11eb-95ef-87c9d10bf5a8.png)

**Comment by lwasser** [comment]
hi  there @mh-skjelvareid  !! What a great observation!! Let me fix that now.  i'm working on some  lesson updates. so  glad you're  finding the  textbook useful. That's super interesting. i've been using `Greys` and `Greys_r` for a while. But  `gray` does look much  better. the lesson is updated and a push is  coming down the pipeline. it should be live within the hour. i'll post here again when it is fixed!

**Comment by lwasser** [comment]
ok! i  just pushed the changes. it may take github  5-10 minutes to  build the updates but it should be fixed. Please reopen if you  still see issues!! thank you so much!

**Comment by mh-skjelvareid** [comment]
Looks good (and fast, too)! :) And thanks for making all your resources openly available, they are super useful for someone (like me) who's just getting into this field. If I come across other issues or find some other way I can contribute, I'll be sure to let you know. 

Keep up the good work!

**Comment by lwasser** [comment]
so great to hear that positive feedback. thank you for it.
